# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9-69X0X1D3O-rfd8q6Vrz4PUHccNgqb
"""

import numpy as np
from prettytable import PrettyTable

friends = ["monika", "sharmi", "ragavi", "ammu"]

expense_matrix = np.zeros((len(friends), len(friends)))
transactions = []

def add_expense(payee, beneficiaries, amount, description,
                split_type="equal", custom_shares=None):

    payee_index = friends.index(payee)

    if split_type == "equal":
        share_per_person = amount / len(beneficiaries)
        shares = {}

        for beneficiary in beneficiaries:
            shares[beneficiary] = share_per_person

    elif split_type == "custom":
        shares = custom_shares

        if abs(sum(shares.values()) - amount) > 0.01:
            print("Error: Custom shares total must equal expense amount.")
            return

    else:
        print("Invalid split type.")
        return

    for beneficiary, share_amount in shares.items():
        beneficiary_index = friends.index(beneficiary)
        expense_matrix[payee_index][beneficiary_index] += share_amount

    transactions.append({
        "description": description,
        "amount": amount,
        "paid_by": payee,
        "split_type": split_type,
        "shares": shares
    })

def calculate_settlements():

    paid = {}
    share = {}

    for friend in friends:
        paid[friend] = 0
        share[friend] = 0

    for transaction in transactions:

        payer = transaction["paid_by"]
        paid[payer] += transaction["amount"]

        for person, amount in transaction["shares"].items():
            share[person] += amount

    settlements = {}

    for friend in friends:
        settlements[friend] = paid[friend] - share[friend]

    return settlements

def display_transactions():

    table = PrettyTable()

    table.field_names = [
        "Description",
        "Amount",
        "Paid By",
        "Split Type",
        "Shares"
    ]

    for transaction in transactions:

        share_details = ", ".join(
            f"{friend}: ₹{amount:.2f}"
            for friend, amount in transaction["shares"].items()
        )

        table.add_row([
            transaction["description"],
            f"₹{transaction['amount']:.2f}",
            transaction["paid_by"],
            transaction["split_type"],
            share_details
        ])

    print(table)

def display_settlements():

    settlements = calculate_settlements()

    table = PrettyTable()
    table.field_names = ["Friend", "Settlement"]

    for friend in friends:

        amount = settlements[friend]

        if amount > 0:
            table.add_row([
                friend,
                f"Should Receive ₹{amount:.2f}"
            ])

        elif amount < 0:
            table.add_row([
                friend,
                f"Owes ₹{-amount:.2f}"
            ])

        else:
            table.add_row([
                friend,
                "Is Settled"
            ])

    print(table)

add_expense(
    "monika",
    ["monika", "sharmi", "ragavi"],
    600,
    "Dinner",
    "equal"
)

add_expense(
    "sharmi",
    ["monika", "sharmi"],
    200,
    "Tea",
    "equal"
)

add_expense(
    "ragavi",
    ["monika", "ragavi", "ammu"],
    500,
    "Cab",
    "custom",
    {
        "monika": 200,
        "ragavi": 200,
        "ammu": 100
    }
)

print("\n========== TRANSACTION HISTORY ==========\n")
display_transactions()

print("\n========== FINAL SETTLEMENT ==========\n")
display_settlements()

from google.colab import drive
drive.mount('/content/drive')